### ISSUE TITLE
Weapon enchants are triggered by thorns

### ISSUE THREAD

**Issue by Shadmage** [nulli0n/GoldenEnchants#12]
Hi

We have found that if a player (A) has the vanilla Thorns enchantment on his/her armour, and another player (B) attacks player A, the thorns triggers enchantments from player A's weapons against player B as if A had attacked B
Tested with: Ice Aspect, Venom, Rocket

**Comment by nulli0n** [comment]
Will be fixed

**Comment by nulli0n** [comment]
Should be fixed now.
