### ISSUE TITLE
Enchants sold in a QuestShop's shop are not translated in info

### ISSUE THREAD

**Issue by Bloodlex** [nulli0n/GoldenEnchants#15]
Hello,

It's an amazing plugin, but I have one issue with translation. I use [QuickShop Reremake plugin](https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-multi-currency.62575/) to create shops and in info it doesn't get translated, although I have a translation in GoldenEnchants file and it's always visible except for this information in shops as in this screenshot:

![image](https://user-images.githubusercontent.com/1086720/112794946-16e46f00-9068-11eb-8e31-f671661db65c.png)

"Aquaman" should be translated to "Wodnik" here.

![image](https://user-images.githubusercontent.com/1086720/112795249-8c503f80-9068-11eb-9ffb-a2d2634b97fd.png)

I'm not sure if I should report it here or on[ QuickShop Reremake](https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-multi-currency.62575/)'s issue page. Could you help me with that? My players are confused with that 🙁  Thanks a lot! 👍

**Comment by nulli0n** [comment]
Enchantments are registered by internal english key names and this can not be changed because of the game limitations (A-Z only). It should be handled by other plugins which is pretty easy to get enchantment key name and add it to the lang config if it's missing. There is nothing I can do.

**Comment by Bloodlex** [comment]
@nulli0n I see, well thanks for the answer 🙂 Do you know perhaps some plugins that can do the job with that? Otherwise this ticket can be closed.

**Comment by nulli0n** [comment]
No plugins can do that for others, each plugin should do it itself.
