### ISSUE TITLE
Could not pass event BlockPlaceEvent

### ISSUE THREAD

**Issue by Bloodlex** [nulli0n/GoldenEnchants#17]
Version: GoldenEnchants v2.10.1
Server: Paper version git-Paper-581 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Hello,

Sometimes I'm getting a following exception in the console: [https://pastebin.com/6HTaVyH8](https://pastebin.com/6HTaVyH8)

Unfortunately, I'm not able to say more details about it, because it seems to happen in random moments. I can't say how to reproduce that, I haven't also noticed impact of that, but I'm worried with those exceptions. Could you please take a look on that 🙁 ?

Other than that, it's an awesome plugin and thank you very much for that! 🙂 

Plugins (67): ActionHealth*, AdvancedLogger*, AdvancedRegionMarket, ArmShopBridge, AsyncWorldEdit, AuthMe, BetterBees, BetterHeads, CommandBlocks, CommandNotifier, CommandPanels, ContainerPassthrough, CraftBook, DeathPenalties, dynmap*, Dynmap-WorldGuard*, EasyCarts, Epidemic, Essentials, EssentialsChat, GoldenEnchants, GSit, Harbor, HolographicDisplays, Images, InteractiveBooks, JetsAntiAFKPro, Jobs, KeepChunks, LangUtils, Lasso, LastLoginAPI, LeaderHeadsRevamped, LogBlock, LuckPerms, LWC, MobArena, MyCommand, NBTAPI, NexEngine, NoElytra*, OpenInv, OreAnnouncer, Orebfuscator, PetMaster, Pingas*, PL-Hide-Pro, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, QuickShopDynmap, RegionRaid, SAML, SkinsRestorer, Spartan, SuperVanish, TAB, TitleManager, TreeAssist, Vault, VillagerOptimiser, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by nulli0n** [comment]
Should be fixed now.

**Comment by Bloodlex** [comment]
Great, thanks! 👍
