### ISSUE TITLE
Chunk corruption and items disappearing with Silk Chest

### ISSUE THREAD

**Issue by Bloodlex** [nulli0n/GoldenEnchants#18]
Version: GoldenEnchants v2.10.1
Server: Paper version git-Paper-581 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Hello,

When you place chests grabbed by silk chest enchant to create a double chest from them, sometimes it causes items to disappear. Could you please take a look on that? 🙁 

I'm also experiencing such **exception and chunk corruption** when using it:

[https://pastebin.com/ru7MW8Ez](https://pastebin.com/ru7MW8Ez)
[https://pastebin.com/eR6YHfFW](https://pastebin.com/eR6YHfFW)

I'm getting **disconnected with all players at the same chunk when deleting chest containing other chests**

**It regenerated my chunks and I lost everything on them 😢 It's a very dangerous enchant for now for the server.**

I think it is because there are to many items on one chunk, more than it expects to be.

Screenshots when disconnected:
![image](https://user-images.githubusercontent.com/1086720/115104949-519d4100-9f5c-11eb-9415-b0524b4c7cbd.png)

Plugins list:
Plugins (67): ActionHealth*, AdvancedLogger*, AdvancedRegionMarket, ArmShopBridge, AsyncWorldEdit, AuthMe, BetterBees, BetterHeads, CommandBlocks, CommandNotifier, CommandPanels, ContainerPassthrough, CraftBook, DeathPenalties, dynmap*, Dynmap-WorldGuard*, EasyCarts, Epidemic, Essentials, EssentialsChat, GoldenEnchants, GSit, Harbor, HolographicDisplays, Images, InteractiveBooks, JetsAntiAFKPro, Jobs, KeepChunks, LangUtils, Lasso, LastLoginAPI, LeaderHeadsRevamped, LogBlock, LuckPerms, LWC, MobArena, MyCommand, NBTAPI, NexEngine, NoElytra*, OpenInv, OreAnnouncer, Orebfuscator, PetMaster, Pingas*, PL-Hide-Pro, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, QuickShopDynmap, RegionRaid, SAML, SkinsRestorer, Spartan, SuperVanish, TAB, TitleManager, TreeAssist, Vault, VillagerOptimiser, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by Bloodlex** [comment]
I'm also experiencing such exception and chunk corruption when using it:

[https://pastebin.com/ru7MW8Ez](https://pastebin.com/ru7MW8Ez)
[https://pastebin.com/eR6YHfFW](https://pastebin.com/eR6YHfFW)

**Comment by nulli0n** [comment]
Should be fixed now.

**Comment by Bloodlex** [comment]
Thanks a lot, we'll test it carefully, but it seems to work now 👍
