### ISSUE TITLE
No build instructions available

### ISSUE THREAD

**Issue by AristocratMC** [nulli0n/GoldenEnchants#2]
Hi @nulli0n, I attempted to re-build this plugin to try and extend the "Tunnel" enchantment to support levels above 1 (so that Tunnel II could dig 3x3 for example), but realized that this plugin has a hard dependency on NexEngine.

I then cloned the NexEngine repo and attempted to build that, but it has labyrinthine dependencies on a ton of plugins that I'm not using on my server, so I'm not sure where to go next. 

If you could provide some sort of workplace setup instructions or a compiled NexEngine jar I could add as a library to allow GoldenEnchants to build properly, it would be appreciated.

**Comment by nulli0n** [comment]
Just added a .jar release for the NexEngine.

**Comment by AristocratMC** [comment]
Thank you very much! I was able to build the plugin successfully with the provided .jar.
