### ISSUE TITLE
Shulkers disappear

### ISSUE THREAD

**Issue by Bloodlex** [nulli0n/GoldenEnchants#20]
Hello,

My players complain, that they shulkers disappear. Is it possible that GoldenEnchants can cause this? We had problems with Silk Chest enchant lately and maybe GoldenEnchants uses some shulker mechanics? If not, then maybe you have some hint how to check that? I don't have any exceptions on the console 🙁 

I would be very grateful for your help. 

Server version: Purpur version git-Purpur-1060 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (66): ActionHealth*, AdvancedLogger*, AdvancedRegionMarket, ArmShopBridge, AsyncWorldEdit, AuthMe, BetterBees, BetterHeads, ChestSort, ClearLag, CommandNotifier, CommandPanels, ContainerPassthrough, CraftBook, DeathPenalties, dynmap*, Dynmap-WorldGuard*, EasyCarts, EntityTrackerFixer, Epidemic, Essentials, EssentialsChat, GoldenEnchants, GSit, Harbor, Images, InteractiveBooks, JetsAntiAFKPro, Jobs, KeepChunks, LangUtils, LastLoginAPI, LogBlock, LuckPerms, LWC, MobArena, MyCommand, NBTAPI, NexEngine, NoElytra*, OpenInv, OreAnnouncer, PetMaster, Pingas*, PL-Hide-Pro, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, QuickShopDynmap, RegionRaid, SAML, SkinsRestorer, Spartan, StackMob, SuperVanish, TAB, TitleManager, TreeAssist, Vault, VillagerOptimiser, WorldEdit, WorldGuard, WorldGuardExtraFlags

Best regards,
Bloodlex

**Comment by nulli0n** [comment]
It does nothing with player items.

**Comment by Bloodlex** [comment]
Okay, thanks 🙂
