### ISSUE TITLE
Enchantments not working with enchantment table

### ISSUE THREAD

**Issue by TheGreat09123** [nulli0n/GoldenEnchants#22]
Hey! I am having trouble and was wondering if you could help!
The enchantments display as blank when they appear in the enchantment table.
I am using default config. What am I doing wrong? 
(plugin list and issue example)
![explorer_gaeIpzFrxn](https://user-images.githubusercontent.com/72113421/117515894-302ce500-af5d-11eb-9936-b59a998fbc88.png)
![javaw_YQRqxYPApa](https://user-images.githubusercontent.com/72113421/117515897-30c57b80-af5d-11eb-9045-63570002cac7.png)

**Comment by nulli0n** [comment]
1. It does not adds enchantments to the table list, only to item after enchanting.
2. It's client-side, so custom enchants names are not visible anyway.

**Comment by TheGreat09123** [comment]
Thanks SOOOO much!
