### ISSUE TITLE
Tunnel and Blast Mining are exclusive? 

### ISSUE THREAD

**Issue by AristocratMC** [nulli0n/GoldenEnchants#3]
I acquired this book via enchantment table: 

![image](https://user-images.githubusercontent.com/34401983/98727250-a6151280-2365-11eb-918a-9e50524323cf.png)

It was then applied to a pickaxe, but the pickaxe received only the "Tunnel I" enchantment. Is this intended?

**Comment by nulli0n** [comment]
Tunnel enchantment defined as a conflict one for the Blast Mining, that's why.

**Comment by AristocratMC** [comment]
A check to prevent conflicting enchantments from ending up on the same book would probably be a good idea then, if that is possible to do.

**Comment by nulli0n** [comment]
Yeah, will do!

**Comment by AristocratMC** [comment]
Fixed in dc130aecaa21ae0fa6a03ee52b47ba0cbef41357
