### ISSUE TITLE
New Enchantment

### ISSUE THREAD

**Issue by Ronnie0982** [nulli0n/GoldenEnchants#7]
New Enchantment to get on Tools Telepathy: Items go to the inventory when breaking blocks

**Comment by nulli0n** [comment]
It's already exist as a Telekinesis

**Comment by Ronnie0982** [comment]
Well yes, that is true
But it will not work even if i turn the radius to a larger number?
Could there be anything wrong The config or enchantment??

![8ADE6527-F1E5-445C-A631-7F5EFA72C007](https://user-images.githubusercontent.com/4800840/104734117-077ba800-5740-11eb-89b1-8082e5780f6a.jpeg)

**Comment by nulli0n** [comment]
It will
